from typing import Protocol

class ConfiguracionRepositoryPort(Protocol):
    def iniciar_catalogo(self, docente: str) -> None: ...
    def sesion_guardar(self, huella: str, docente: str, vence: float) -> None: ...
    def sesion_obtener(self, huella: str) -> tuple[str, float] | None: ...
    def sesion_borrar(self, huella: str) -> None: ...
    def cursos(self, docente: str) -> list[dict]: ...
    def curso_guardar(self, docente: str, curso: dict) -> None: ...
    def documentos(self, docente: str) -> list[dict]: ...
    def documento_guardar(self, docente: str, datos: dict, contenido: bytes) -> None: ...
    def documento_obtener(self, docente: str, id: str) -> tuple[dict, bytes] | None: ...
    def documento_borrar(self, docente: str, id: str) -> None: ...
    def historial(self, docente: str) -> list[dict]: ...
    def propietario_generacion(self, id: str) -> str | None: ...
