from typing import Any, Protocol

class GeneracionRepositoryPort(Protocol):
    def catalogo_demo(self) -> dict[str, Any]: ...
    def guardar(self, resultado: dict[str, Any]) -> None: ...
    def obtener(self, generacion_id: str) -> dict[str, Any] | None: ...
