"""Puerto de la revisión docente: recursos generados y su revisión, e historial de descargas."""
from typing import Protocol


class RevisionRepositoryPort(Protocol):
    def recursos_de_unidad(self, docente: str, unidad_id: str) -> list[dict]: ...
    def recurso_obtener(self, docente: str, recurso_id: str) -> dict | None: ...
    def recursos_guardar(self, docente: str, unidad_id: str, recursos: list[dict]) -> None: ...
    def recurso_borrar(self, docente: str, recurso_id: str) -> None: ...
    def descargas(self, docente: str, unidad_id: str) -> list[dict]: ...
    def descarga_guardar(self, docente: str, unidad_id: str, descarga: dict) -> None: ...
    def descargas_borrar(self, docente: str, unidad_id: str) -> None: ...
