import { expect, test } from '@playwright/test';
import { mkdirSync } from 'node:fs';
const evidence = 'test-results/HU-045';
mkdirSync(evidence, { recursive: true });
test('HU-045 sesión, cursos, unidades y persistencia', async ({ page }) => {
  await page.goto('/cursos');
  await expect(page).toHaveURL(/login/);
  await page.keyboard.press('Tab');
  await expect(page.getByRole('link', { name: 'Saltar al contenido' })).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(page.getByLabel('Modo de acceso')).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(page.getByLabel('Correo electrónico')).toBeFocused();
  await expect.poll(() => page.getByLabel('Correo electrónico').evaluate((el) => getComputedStyle(el).outlineColor)).toBe('rgb(22, 53, 44)');
  await page.screenshot({ path: `${evidence}/01-login.png`, fullPage: true });
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await expect(page.getByRole('alert')).toContainText('correo electrónico válido');
  await page.getByLabel('Correo electrónico').fill('docente@5e.demo');
  await page.getByLabel('Contraseña', { exact: true }).fill('incorrecta');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await expect(page.getByRole('alert')).toContainText('Correo o contraseña incorrectos');
  await page.screenshot({ path: `${evidence}/02-error-login.png`, fullPage: true });
  await page.getByLabel('Contraseña', { exact: true }).fill('Demo5E!2026');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await expect(page.getByRole('heading', { name: 'Cursos y unidades', exact: true })).toBeVisible();
  await page.getByLabel('Código del curso').fill('BIO101');
  await page.getByLabel('Nombre del curso').fill('Biología de demostración');
  await page.getByLabel('Periodo académico').fill('2026-II');
  await page.getByLabel('Unidad 1', { exact: true }).fill('La célula');
  await page.getByRole('button', { name: 'Añadir unidad' }).click();
  await page.getByLabel('Unidad 2', { exact: true }).fill('Ecosistemas');
  await page.getByRole('button', { name: 'Crear curso', exact: true }).click();
  const course = page.getByRole('article', { name: 'Biología de demostración' });
  await expect(course).toContainText('Unidad 2: Ecosistemas');
  await page.screenshot({ path: `${evidence}/03-curso-creado.png`, fullPage: true });
  await course.getByRole('button', { name: 'Editar curso' }).click();
  await page.getByLabel('Nombre del curso').fill('Biología general');
  await page.getByLabel('Unidad 2', { exact: true }).fill('Ecología');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.reload();
  await expect(page.getByRole('article', { name: 'Biología general' })).toContainText('Unidad 2: Ecología');
  await page.screenshot({ path: `${evidence}/04-curso-editado.png`, fullPage: true });
  await expect.poll(() => page.evaluate(() => JSON.stringify(localStorage).includes('Demo5E!2026'))).toBe(false);
  for (const width of [1280, 820, 375]) {
    await page.setViewportSize({ width, height: 900 });
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: `${evidence}/05-cursos-${width}.png`, fullPage: true });
  }
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.getByRole('button', { name: 'Cerrar sesión' }).click();
  await page.goto('/revision');
  await expect(page).toHaveURL(/login/);
  await page.keyboard.press('Tab');
  await expect(page.getByRole('link', { name: 'Saltar al contenido' })).toBeFocused();
});
