import { expect, test } from '@playwright/test';
import { mkdirSync } from 'node:fs';
// Esta prueba se ejecuta con playwright.api.config.ts, que levanta ambos servidores.
const evidence = '../docs/evidencias/HU-053';
mkdirSync(evidence, { recursive: true });
test('HU-053 solicitud HTTP real, persistencia, evidencia y fallo sin borrar decisiones', async ({ page, request }) => {
  await page.goto('/login');
  await page.getByLabel('Correo electrónico').fill('docente@5e.demo');
  await page.getByLabel('Contraseña', { exact: true }).fill('Demo5E!2026');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.goto('/configuracion');
  await page.getByLabel('Origen de las propuestas').selectOption('api_demo');
  await page.getByLabel('Público objetivo / Ciclo').fill('Estudiantes de tercer ciclo');
  await page.getByLabel('Competencia a desarrollar').fill('Pensamiento crítico');
  await page.getByLabel('Evaluar (Evaluate)', { exact: false }).check();
  await page.getByLabel('Cantidad de recursos').selectOption('2');
  await page.screenshot({ path: `${evidence}/01-configuracion-api.png`, fullPage: true });
  const response = page.waitForResponse((r) => r.url().endsWith('/api/v1/generaciones') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Solicitar propuestas a la API' }).click();
  const http = await response;
  expect(http.status()).toBe(200);
  const data = await http.json();
  expect(data.request).toMatchObject({ stage: 'evaluate', quantity: 2, audience: 'Estudiantes de tercer ciclo' });
  expect(data.resources).toHaveLength(2);
  await expect(page.getByRole('status').filter({ hasText: '2 recurso(s)' })).toBeVisible();
  await page.screenshot({ path: `${evidence}/02-respuesta-api.png`, fullPage: true });
  const persisted = await request.get(`http://127.0.0.1:8000/api/v1/generaciones/${data.request.id}`);
  expect((await persisted.json()).request.id).toBe(data.request.id);
  await page.getByRole('link', { name: 'Ir a revisión' }).click();
  await expect(page.getByText('Propuesta recibida de la API de demostración')).toBeVisible();
  await expect(page.getByText('Fragmento api-demo:', { exact: false })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Evidencia de origen' })).toBeVisible();
  await page.screenshot({ path: `${evidence}/03-revision-evidencia.png`, fullPage: true });
  const before = await page.evaluate(() => JSON.parse(localStorage.getItem('plataforma5e.demo.v1')!).resources);
  expect(before.filter((r: { source: string }) => r.source === 'api_demo').every((r: { status: string }) => r.status === 'pendiente')).toBe(true);
  await page.reload();
  await expect(page.getByText('Propuesta recibida de la API de demostración')).toBeVisible();
  await page.goto('/configuracion');
  // Error de conexión reproducible sin apagar ni modificar los datos del servidor.
  await page.route('**/api/v1/generaciones', (route) => route.abort('connectionfailed'));
  await page.getByRole('button', { name: 'Solicitar propuestas a la API' }).click();
  await expect(page.getByRole('alert')).toContainText('CONEXION_FALLIDA');
  await expect(page.getByRole('button', { name: 'Solicitar propuestas a la API' })).toBeEnabled();
  await page.screenshot({ path: `${evidence}/04-error-conexion.png`, fullPage: true });
  const after = await page.evaluate(() => JSON.parse(localStorage.getItem('plataforma5e.demo.v1')!).resources);
  expect(after).toEqual(before);
  await page.unroute('**/api/v1/generaciones');
  await page.getByRole('button', { name: 'Solicitar propuestas a la API' }).click();
  await expect(page.getByRole('status').filter({ hasText: '2 recurso(s)' })).toBeVisible();
});
